# Installing numpy

In [34]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


# Importing numpy

In [35]:
import numpy as np

# Creating an array

## 0-D arrays

In [36]:
a = np.array(1)
a.ndim

0

## 1-D arrays

In [37]:
my_array = np.array([1, 2, 3])
array_of_ones = np.ones(10)
array_of_zeros = np.zeros(10)

In [38]:
print(my_array, my_array.ndim, my_array.shape)
print(array_of_ones, array_of_ones.ndim, array_of_ones.shape)
print(array_of_zeros, array_of_ones.ndim, array_of_zeros.shape)

[1 2 3] 1 (3,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 1 (10,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 1 (10,)


## 2-D arrays

In [39]:
my_2d_array = np.array([[1, 2], [3, 4], [5, 6]])
my_2d_array.ndim, my_2d_array.shape

(2, (3, 2))

In [40]:
ones_in_2d = np.ones((10, 2))
ones_in_2d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## Array indexing

In [56]:
print(my_array[0])
print(my_2d_array[1, 1]) # row's index = 1, columns index = 1

1
4


Accessing values based on a condition

In [58]:
my_array[my_array % 2 == 1]

array([1, 3])

In [59]:
my_2d_array[my_2d_array > 2]

array([3, 4, 5, 6])

We can also using negative indexing to start counting from the end

## Array Slicing

The slice format is [start:end:step] <br>
- if start is left empty, we start from 0 <br>
- if end is left empty, we reach the end <br>
- if step is left empty, we take 1 

In [66]:
print(my_2d_array[1, :])
print(my_2d_array[1:3, :2])
print(my_2d_array[::2, 1]) # second column of rows with even index

[3 4]
[[3 4]
 [5 6]]
[2 6]


Negative Slicing Example

In [69]:
my_2d_array[-1, :-1]

array([5])

## Data types

In [77]:
print(np.array(1).dtype)
print(np.array(1.).dtype)
print(np.array("hello").dtype)
print(np.array(1+2j).dtype)
print(np.array(True).dtype)

int64
float64
<U5
complex128
bool
